### ISSUE TITLE
Ask if we can use reilleya's tablet for real

### ISSUE THREAD

**Issue by eric-wieser** [skrub-wreckers/software#8]
Both @reilleya and staff

This worked well enough with the teensy when tried last night

**Comment by eric-wieser** [comment]
This worked well enough with the teensy when tried last night

**Comment by KevinMorrow** [comment]
This is fucking bullshit.

Kevin Morrow
AeroAstro Class of 2018
Massachusetts Institute of Technology

**Comment by KevinMorrow** [comment]
You can't just delete our shit and remake it on GitHub just because you
like it more. WTF?

Kevin Morrow
AeroAstro Class of 2018
Massachusetts Institute of Technology

**Comment by eric-wieser** [comment]
This has been Oked - we're good to go
